### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by eomasters-repos** [Evoland-Land-Monitoring-Evolution/sentinel2_superresolution#11]
The LICENSE file says it is Apache License 2.0, but in the run.py it is AGPL?
https://github.com/Evoland-Land-Monitoring-Evolution/sentinel2_superresolution/blob/83fa1ba00e3fdea82dca71bb3ba744013e98cfa3/src/sentinel2_superresolution/run.py#L77

Which is the correct one?

A nice project, by the way.

**Comment by jmichel-otb** [comment]
Licence is indeed Apache 2.0 and this is a glitch in the code.

Fixed in https://github.com/Evoland-Land-Monitoring-Evolution/sentinel2_superresolution/commit/6fd0befc49986823d6fd55044cd5653fc101e2b3
