### ISSUE TITLE
Unable to Generate Index Layers (NDVI, NDWI) with Correct Pixel Values

### ISSUE THREAD

**Issue by khlaifiabilel** [Evoland-Land-Monitoring-Evolution/sentinel2_superresolution#12]
I am encountering difficulties while trying to generate layers of indexes such as NDVI, NDWI, and others from Supe Resolved Sentinel-2 images. Despite following the standard extraction methods, the pixel values in the generated layers do not match the expected scale provided by the regular methods using standard Sentinel-2 images.

Can you help me with that please

**Comment by jmichel-otb** [comment]
Can you be more specific about the behaviour you observe vs. what you expect ? Like giving command-line samples, screenshots or examples of pixel values ? 

Also, did you pay attention to band order ? As per the FAQ in the doc:

Bands in output image follow the following order: B2, B3, B4, B8, B5, B6, B7, B8A, B11, B12

**Comment by jmichel-otb** [comment]
Closing this issue since I got no answer.
