### ISSUE TITLE
Distortions on chunk edges

### ISSUE THREAD

**Issue by charalamm** [Evoland-Land-Monitoring-Evolution/sentinel2_superresolution#13]
Hello,

First of all, tanks for this incredible package! It feels like magic.

I have noticed some distortions on the final image, on the edges of the chunks. Also I noticed these distortions are less and less when using higher values in `--tile_size` and they finally disappear when using a value that is higher than the tile length. I might need to add that I am not using images from theia but I have made it work with tiles originally from sentinelhub by overriding the `Sentinel2` class.

Is there something I might be doing wrong?

Here is an example of such distortions:
![image](https://github.com/user-attachments/assets/ef0b48e0-9dc9-495b-8ee0-c1cee0ee8b04)

**Comment by jmichel-otb** [comment]
Hi, and thank you for the feedback.

Can you post the complete command line here ?

The `--overlap` (`-ov`) parameter is here to control the margin to infer patches, so as to be sure that only pixels with a complete receptive field are used in the output. It is tuned for the model, if you change this value it can lead to this kind of artifacts.

Also, if you display your images in qgis, beware that it can sometimes display this kind of artifact if you use resampling different than nearest neighbors and are passed the 1:1 resolution (there is a button for getting back to 1:1 in the toolbar).

**Comment by jmichel-otb** [comment]
You're welcome.

Note that pixels from the edge of the whole image are deleted because they do not have a complete receptive field. This should only occur at the edge of the full product (not if using roi / roip).
