### ISSUE TITLE
Error when trying to install gpu version

### ISSUE THREAD

**Issue by firmanhadi** [Evoland-Land-Monitoring-Evolution/sentinel2_superresolution#2]
Hi, 
I got this error message when I tried to install gpu version:
```
Running command git clone --filter=blob:none --quiet 'https://framagit.org/jmichel-otb/sentinel2_superresolution.git[gpu]' /tmp/pip-req-build-h3wkpcmt
  fatal: unable to update url base from redirection:
    asked for: https://framagit.org/jmichel-otb/sentinel2_superresolution.git[gpu]/info/refs?service=git-upload-pack
     redirect: https://framagit.org/users/sign_in
  error: subprocess-exited-with-error
```

**Comment by jmichel-otb** [comment]
Can you try:

```bash
$ git clone https://framagit.org/jmichel-otb/sentinel2_superresolution.git
$ pip install sentinel2_superresolution[gpu]
```

**Comment by firmanhadi** [comment]
> Can you try:
> 
> ```shell
> $ git clone https://framagit.org/jmichel-otb/sentinel2_superresolution.git
> $ pip install sentinel2_superresolution[gpu]
> ```
Thank you for prompt reply. It's running now.

**Comment by jmichel-otb** [comment]
What is your python version ? I think 3.10 is required for this syntax.

**Comment by firmanhadi** [comment]
> What is your python version ? I think 3.10 is required for this syntax.

Thank you. After I used Python 3.10, I could install it. Another error came after I tried to run it.

`File "/home/firman/anaconda3/envs/super/lib/python3.10/site-packages/sensorsio/sentinel2.py", line 404, in build_xml_path
    raise FileNotFoundError(
FileNotFoundError: Could not find root XML file in product directory S2A_MSIL2A_20240319T025531_N0510_R032_T48MYU_20240319T072558.SAFE`

**Comment by nyinyinyanlin** [comment]
I had the same problem with `pip install git+https` combination with the installation redirected to `https://framagit.org/users/sign_in` when supplied [gpu] support variant.o

**Comment by firmanhadi** [comment]
> > What is your python version ? I think 3.10 is required for this syntax.
> 
> Thank you. After I used Python 3.10, I could install it. Another error came after I tried to run it with this command: `sentinel2_superesolution -i S2A_MSIL2A_20240319T025531_N0510_R032_T48MYU_20240319T072558.SAFE -o resumts/ --gpu`
> 
> `File "/home/firman/anaconda3/envs/super/lib/python3.10/site-packages/sensorsio/sentinel2.py", line 404, in build_xml_path raise FileNotFoundError( FileNotFoundError: Could not find root XML file in product directory S2A_MSIL2A_20240319T025531_N0510_R032_T48MYU_20240319T072558.SAFE`

I realized I didn't use the correct version of Sentinel-2A Product. I downloaded Sentinel-2A MAJA product from DLR, but when I ran it again, there was a new error message:

`sentinel2_superesolution -i SENTINEL2B_20240418-103602-534_L2A_T32UNE_C_V1-3 -o resumts/ --gpu
Traceback (most recent call last):
  File "/home/firman/anaconda3/envs/super/bin/sentinel2_superesolution", line 8, in <module>
    sys.exit(run())
  File "/home/firman/anaconda3/envs/super/lib/python3.10/site-packages/sentinel2_superresolution/run.py", line 424, in run
    main(sys.argv[1:])
  File "/home/firman/anaconda3/envs/super/lib/python3.10/site-packages/sentinel2_superresolution/run.py", line 281, in main
    ort_session = ort.InferenceSession(args.model, sess_options=so, providers=ep_list)
  File "/home/firman/anaconda3/envs/super/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/firman/anaconda3/envs/super/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /home/firman/anaconda3/envs/super/lib/python3.10/site-packages/sentinel2_superresolution/../../models/carn_3x3x64g4sw_bootstrap.onnx failed:Load model /home/firman/anaconda3/envs/super/lib/python3.10/site-packages/sentinel2_superresolution/../../models/carn_3x3x64g4sw_bootstrap.onnx failed. File doesn't exist`

**Comment by firmanhadi** [comment]
> ```shell
> $ git clone https://framagit.org/jmichel-otb/sentinel2_superresolution.git
> $ pip install sentinel2_superresolution[gpu]
> ```
You can try to use the solution mentioned by @jmichel-otb :

$ git clone https://framagit.org/jmichel-otb/sentinel2_superresolution.git

$ pip install sentinel2_superresolution[gpu]

**Comment by firmanhadi** [comment]
> I had the same problem with `pip install git+https` combination with the installation redirected to `https://framagit.org/users/sign_in` when supplied [gpu] support variant.o

You can use the solution by @jmichel-otb https://github.com/Evoland-Land-Monitoring-Evolution/sentinel2_superresolution/issues/2#issuecomment-2082311191

**Comment by jmichel-otb** [comment]
> I realized I didn't use the correct version of Sentinel-2A Product. I downloaded Sentinel-2A MAJA product from DLR, but when I ran it again, there was a new error message:

Yes, supporting sen2corr L2A is only a matter of adding support in sensorsio. Should be available in a few weeks / months.

> `sentinel2_superesolution -i SENTINEL2B_20240418-103602-534_L2A_T32UNE_C_V1-3 -o resumts/ --gpu Traceback (most recent call last): File "/home/firman/anaconda3/envs/super/bin/sentinel2_superesolution", line 8, in <module> sys.exit(run()) File "/home/firman/anaconda3/envs/super/lib/python3.10/site-packages/sentinel2_superresolution/run.py", line 424, in run main(sys.argv[1:]) File "/home/firman/anaconda3/envs/super/lib/python3.10/site-packages/sentinel2_superresolution/run.py", line 281, in main ort_session = ort.InferenceSession(args.model, sess_options=so, providers=ep_list) File "/home/firman/anaconda3/envs/super/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__ self._create_inference_session(providers, provider_options, disabled_optimizers) File "/home/firman/anaconda3/envs/super/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model) onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /home/firman/anaconda3/envs/super/lib/python3.10/site-packages/sentinel2_superresolution/../../models/carn_3x3x64g4sw_bootstrap.onnx failed:Load model /home/firman/anaconda3/envs/super/lib/python3.10/site-packages/sentinel2_superresolution/../../models/carn_3x3x64g4sw_bootstrap.onnx failed. File doesn't exist`

Ok, so there is still a problem with installation, the model file does not get installed with `pip install`. Sorry about the crappy packaging, I need to improve it.

Meanwhile, could you try running again:

```bash
$ git clone https://framagit.org/jmichel-otb/sentinel2_superresolution.git
$ pip install -e sentinel2_superresolution[gpu]
```
Or alternatively provide the model explicitly to the command-line:


```bash
$ sentinel2_superesolution -i SENTINEL2B_20240418-103602-534_L2A_T32UNE_C_V1-3 -o resumts/ --gpu -m path_to/carn_3x3x64g4sw_bootstrap.onnx
```
The `carn_3x3x64g4sw_bootstrap.onnx` model file is located in the `models` folder of the source of `sentinel2_superresolution`.

**Comment by safalabolo** [comment]
Hi @jmichel-otb, 
thnak you for your quick reply.
Unfortunately, a new error occurs again.

**sentinel2_superesolution -v -i /mnt/hd/appoggio2/test/S2B_MSIL1C_20230823T095559_N0509_R122_T33TUG_20230823T121626.SAFE/ --l1c -o out/ --gpu -m /test/carn_3x3x64g4sw_bootstrap.onnx**
Traceback (most recent call last):
  File "/usr/local/bin/sentinel2_superesolution", line 5, in <module>
    from sentinel2_superresolution.run import run
  File "/root/miniconda3/lib/python3.10/site-packages/sentinel2_superresolution/run.py", line 15, in <module>
    from sensorsio.sentinel2 import Sentinel2
  File "/root/miniconda3/lib/python3.10/site-packages/sensorsio/sentinel2.py", line 27, in <module>
    import geopandas as gpd
  File "/mnt/hd/safalabolo/.local/lib/python3.10/site-packages/geopandas/__init__.py", line 1, in <module>
    from geopandas._config import options
  File "/mnt/hd/safalabolo/.local/lib/python3.10/site-packages/geopandas/_config.py", line 109, in <module>
    default_value=_default_use_pygeos(),
  File "/mnt/hd/safalabolo/.local/lib/python3.10/site-packages/geopandas/_config.py", line 95, in _default_use_pygeos
    import geopandas._compat as compat
  File "/mnt/hd/safalabolo/.local/lib/python3.10/site-packages/geopandas/_compat.py", line 242, in <module>
    import rtree  # noqa: F401
  File "/root/miniconda3/lib/python3.10/site-packages/rtree/__init__.py", line 9, in <module>
    from .index import Index, Rtree  # noqa
  File "/root/miniconda3/lib/python3.10/site-packages/rtree/index.py", line 17, in <module>
    from . import core
  File "/root/miniconda3/lib/python3.10/site-packages/rtree/core.py", line 74, in <module>
    rt = finder.load()
  File "/root/miniconda3/lib/python3.10/site-packages/rtree/finder.py", line 79, in load
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

**Comment by firmanhadi** [comment]
> > I realized I didn't use the correct version of Sentinel-2A Product. I downloaded Sentinel-2A MAJA product from DLR, but when I ran it again, there was a new error message:
> 
> Yes, supporting sen2corr L2A is only a matter of adding support in sensorsio. Should be available in a few weeks / months.
> 
> > `sentinel2_superesolution -i SENTINEL2B_20240418-103602-534_L2A_T32UNE_C_V1-3 -o resumts/ --gpu Traceback (most recent call last): File "/home/firman/anaconda3/envs/super/bin/sentinel2_superesolution", line 8, in <module> sys.exit(run()) File "/home/firman/anaconda3/envs/super/lib/python3.10/site-packages/sentinel2_superresolution/run.py", line 424, in run main(sys.argv[1:]) File "/home/firman/anaconda3/envs/super/lib/python3.10/site-packages/sentinel2_superresolution/run.py", line 281, in main ort_session = ort.InferenceSession(args.model, sess_options=so, providers=ep_list) File "/home/firman/anaconda3/envs/super/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__ self._create_inference_session(providers, provider_options, disabled_optimizers) File "/home/firman/anaconda3/envs/super/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model) onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /home/firman/anaconda3/envs/super/lib/python3.10/site-packages/sentinel2_superresolution/../../models/carn_3x3x64g4sw_bootstrap.onnx failed:Load model /home/firman/anaconda3/envs/super/lib/python3.10/site-packages/sentinel2_superresolution/../../models/carn_3x3x64g4sw_bootstrap.onnx failed. File doesn't exist`
> 
> Ok, so there is still a problem with installation, the model file does not get installed with `pip install`. Sorry about the crappy packaging, I need to improve it.
> 
> Meanwhile, could you try running again:
> 
> ```shell
> $ git clone https://framagit.org/jmichel-otb/sentinel2_superresolution.git
> $ pip install -e sentinel2_superresolution[gpu]
> ```
> 
> Or alternatively provide the model explicitly to the command-line:
> 
> ```shell
> $ sentinel2_superesolution -i SENTINEL2B_20240418-103602-534_L2A_T32UNE_C_V1-3 -o resumts/ --gpu -m path_to/carn_3x3x64g4sw_bootstrap.onnx
> ```
> 
> The `carn_3x3x64g4sw_bootstrap.onnx` model file is located in the `models` folder of the source of `sentinel2_superresolution`.

I have finally succeeded to run it and get the result. 
![super](https://github.com/Evoland-Land-Monitoring-Evolution/sentinel2_superresolution/assets/7415563/cf231e99-a215-4049-aa68-07ffeb520e04)

**Comment by jmichel-otb** [comment]
Packaging is fixed and installation instruction have been simplified in README.
