### ISSUE TITLE
The bands of the super resolution product

### ISSUE THREAD

**Issue by firmanhadi** [Evoland-Land-Monitoring-Evolution/sentinel2_superresolution#4]
I have finally succeeded in getting the super resolution product. 
The file has 10 bands. I got RGB True Color by combining band 3,2 and 1, which is different for the original Sentinel-2A (RGB 432).
Is there any documentation regarding the look up table of the bands of super resolution product?
For example, Band 1 equal to Band 2 in the original Sentinel-2, etc.
Thanks.

**Comment by jmichel-otb** [comment]
Band order is: B2, B3, B4, B8, B5, B6, B7, B8A, B11, B12

**Comment by paugalles** [comment]
Note that in the readme B06 is repeated rather than including B07. I assume that's a typo. It says:
`B02, B03, B04, B05, B06, B06, B08, B8A, B11 and B12`

**Comment by jmichel-otb** [comment]
Noted. I am planning an update to address the different issues (doc and installation) soon.

**Comment by jmichel-otb** [comment]
A FAQ section has been added in README with this information.
