### ISSUE TITLE
SRE (Surface reflectance without terrain correction)  or FRE (Flat reflectance (with terrain correction) bands?

### ISSUE THREAD

**Issue by safalabolo** [Evoland-Land-Monitoring-Evolution/sentinel2_superresolution#8]
Hi,
Super resolution is applied to the bands
SRE (Surface reflectance without terrain correction) 
or FRE (Flat reflectance (with terrain correction))
S2L2A Theia?
Thank you.

**Comment by jmichel-otb** [comment]
FRE bands are used.

**Comment by jmichel-otb** [comment]
A FAQ section has been added in README with this information.

**Comment by safalabolo** [comment]
Hi,
I noticed that the super-resolution product (5m_SISR) contains bands with negative values, and the same occurs with the original data (5m_bicubic).

This does not surprise me (https://www.cesbio.cnrs.fr/multitemp/can-surface-reflectance-be-negative/), but isn't the input data for the super-resolution process SRE rather than FRE? (https://www.theia-land.fr/wp-content/uploads/2018/12/SENTINEL-2A_L2A_Products_Description.pdf)

Am I mistaken?
Thank you.
